export { default as Navbar } from './Navbar/Navbar'
export { default as InfoSection } from './InfoSection/InfoSection'
export { default as Footer} from './Footer/Footer'
export { default as HomeSection} from './HomePanel/HomeSection'
export { default as InfoHRFHome} from './InfoHRFHome/InfoHRFHome'
export { default as CustomersHome} from './CustomersHome/CustomersHome'
