export { default as Navbar } from './Navbar/Navbar'
export { default as InfoSection } from './InfoSection/InfoSection'
export { default as Footer} from './Footer/Footer'
export { default as InfoHRFHome} from './InfoHRFHome/InfoHRFHome'
export { default as CustomersHome} from './CustomersHome/CustomersHome'
export { default as ServicePlans} from './ServicePlans/ServicePlans'
export { default as FormContact} from './FormContact/FormContact'
export { default as Location} from './Location/Location'
export { default as Hero } from './Hero/Hero'
export { default as PanelService } from './PanelService/PanelService'
export { default as IconContacts } from './IconContacts/IconContacts'
export { default as AboutUsComponent } from './AboutUsComponent/AboutUsComponent'
export { default as OrganizationalDNA } from './OrganizationalDNA/OrganizationalDNA'
export { default as Values } from './Values/Values'
export { default as Team } from './Team/Team'
export { default as MenuNetworks } from './menuNetworks/menuNetworks'